const FooterPlaces = [
    {
        id:1,
        placeName:"Canmore",
        placetype:"Kiralık daireler",
        category:"Popüler",
    },
    {
        id:2,
        placeName:"Marbella",
        placetype:"Kiralık evler",
        category:"Popüler",
    },
    {
        id:3,
        placeName:"Prescott",
        placetype:"Kiralık tatil yerleri",
        category:"Popüler",
    },
    {
        id:4,
        placeName:"Tucson",
        placetype:"Kiralık tatil yerleri",
        category:"Popüler",
    },
    {
        id:5,
        placeName:"Mallacoota",
        placetype:"Evcil hayvan dostu kiralık yerler",
        category:"Popüler",
    },
    {
        id:6,
        placeName:"Mountain View",
        placetype:"Kiralık kulübeler",
        category:"Popüler",
    },
    {
        id:7,
        placeName:"Anaheim",
        placetype:"Kiralık daireler",
        category:"Popüler",
    },
    {
        id:8,
        placeName:"Sonoma",
        placetype:"Kiralık tatil yerleri",
        category:"Popüler",
    },
    {
        id:9,
        placeName:"Dubai",
        placetype:"Kiralık evler",
        category:"Popüler",
    },
    {
        id:10,
        placeName:"Brighton",
        placetype:"Evcil hayvan dostu kiralık yerler",
        category:"Popüler",
    },
    {
        id:11,
        placeName:"Newcastle upon Tyne",
        placetype:"Kiralık daireler",
        category:"Popüler",
    },
    {
        id:12,
        placeName:"South West England",
        placetype:"Kiralık kulübeler",
        category:"Popüler",
    },
    {
        id:13,
        placeName:"Fort Myers",
        placetype:"Kiralık evler",
        category:"Popüler",
    },
    {
        id:14,
        placeName:"Kissimmee",
        placetype:"Kiralık kır evleri",
        category:"Popüler",
    },
    {
        id:15,
        placeName:"Orlando",
        placetype:"Kiralık tatil yerleri",
        category:"Popüler",
    },
    {
        id:16,
        placeName:"St. Augustine",
        placetype:"Denize sıfır kiralık yerler",
        category:"Popüler",
    },
    {
        id:17,
        placeName:"Dahlonega",
        placetype:"Kiralık kır evleri",
        category:"Popüler",
    },
    {
        id:18,
        placeName:"O‘ahu",
        placetype:"Sahil sitelerinde kiralık konutlar",
        category:"Popüler",
    },
    {
        id:19,
        placeName:"Bar Harbor",
        placetype:"Kiralık tatil yerleri",
        category:"Popüler",
    },
    {
        id:20,
        placeName:"Phoenix",
        placetype:"Kiralık evler",
        category:"Sanat ve kültür",
    },
    {
        id:21,
        placeName:"Los Angeles",
        placetype:"Oda-kahvaltılar",
        category:"Sanat ve kültür",
    },
    {
        id:22,
        placeName:"San Francisco",
        placetype:"Kiralık tatil yerleri",
        category:"Sanat ve kültür",
    },
    {
        id:23,
        placeName:"Prag",
        placetype:"Kiralık tatil yerleri",
        category:"Sanat ve kültür",
    },
    {
        id:24,
        placeName:"Hot Springs",
        placetype:"Kiralık kulübeler",
        category:"Sanat ve kültür",
    },
    {
        id:25,
        placeName:"San Diego",
        placetype:"Kiralık bungalovlar",
        category:"Sanat ve kültür",
    },
    {
        id:26,
        placeName:"Barselona",
        placetype:"Kiralık tatil yerleri",
        category:"Sanat ve kültür",
    },
    {
        id:27,
        placeName:"Washington",
        placetype:"Kiralık daireler",
        category:"Sanat ve kültür",
    },
    {
        id:28,
        placeName:"Lake Martin",
        placetype:"Evcil hayvan dostu kiralık yerler",
        category:"Açık hava",
    },
    {
        id:29,
        placeName:"Mentone",
        placetype:"Kiralık tatil yerleri",
        category:"Dağlar",
    },
    {
        id:30,
        placeName:"Dauphin Island",
        placetype:"Havuzlu kiralık yerler",
        category:"Sahil",
    },
    {
        id:31,
        placeName:"Muhteşem havuzlar",
        category:"Kategoriler",
    },
    {
        id:32,
        placeName:"Kamp",
        category:"Kategoriler",
    },
    {
        id:33,
        placeName:"Kuzey Kutbu",
        category:"Kategoriler",
    },
    {
        id:34,
        placeName:"Londra",
        placetype:"İngiltere",
        category:"Yapılacak şeyler",
    },
]
export default FooterPlaces;